[test1是将try catch放在了循环内，test2是将try catch放在了循环外:区别是一个在执行中抛出异常会继续循环]
web link: https://blog.csdn.net/lihb018/article/details/8165174





